version: '3.3'
services:

  kafka:
    image: confluentinc/cp-kafka:3.3.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'

  zookeeper:
    image: confluentinc/cp-zookeeper:3.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'

  schema-registry:
    image: confluentinc/cp-schema-registry:3.3.0
    hostname: schema-registry
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8082:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8082

  kms:
    image: skyuk/kafka-message-scheduler:0.9.0-SNAPSHOT
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
      SCHEDULE_TOPIC: schedules
    ports:
      - "9095:9095"
